name: dni_reader
description: Módulo para leer códigos PDF417 de DNI argentino.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Architecture
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.0
  internet_connection_checker: ^1.0.0+1
  http: ^1.1.0

  # State management
  flutter_bloc: ^8.1.3

  # Barcode
  mobile_scanner: ^3.5.5
  pdf417: ^1.1.1

  # UI
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.6
  bloc_test: ^9.1.4

flutter:
  uses-material-design: true